### ISSUE TITLE
Error when using %DateTime% after %Context%

### ISSUE THREAD

**Issue by apropl** [fernandodsanjos/BizTalk.PipelineComponents.CustomMacros#1]
If you use both the context variable and the datetime variable an issue can occur.
It depends on which order you use them.

The following does not work:
%Context(CST.YouContextValue)%%DateTime(yyyyMMdd)%

Error message in BizTalk:
The FILE send adapter cannot open file C:\your\sendport\path\ for writing.
 Details: The system cannot find the path specified.

This works:
%DateTime(yyyyMMdd)%%Context(CST.YouContextValue)%

**Comment by fernandodsanjos** [comment]
Fixed
